# -*- coding: utf-8 -*-
"""dasboards.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n5f5fVe_RhoQFX9UenoO3PkjpZoOIOvs
"""

df.infor()

import zipfile
import pandas as pd

# Unzip the file
with zipfile.ZipFile("archive.zip", "r") as zip_ref:
    zip_ref.extractall()

# Load the Excel file
df = pd.read_excel("Telco_customer_churn.xlsx")

df.info()

df['Churn'].value_counts()
df.head()

df.columns.tolist()

[col for col in df.columns if 'churn' in col.lower()]

df['Churn Label'].value_counts()

df.groupby('Tenure Months')['Churn Label'].value_counts(normalize=True).unstack()['Yes']

df.groupby('Contract')['Churn Label'].value_counts(normalize=True).unstack()['Yes']

df.groupby('Internet Service')['Churn Label'].value_counts(normalize=True).unstack()['Yes']

import matplotlib.pyplot as plt

churn_by_internet = df.groupby('Internet Service')['Churn Label'].value_counts(normalize=True).unstack()['Yes'] * 100

churn_by_internet.plot(kind='bar', color=['#4CAF50', '#FF9800', '#F44336'])
plt.title('Churn Rate by Internet Service')
plt.ylabel('Churn Rate (%)')
plt.xlabel('Internet Service')
plt.xticks(rotation=0)
plt.show()

churn_by_contract=df.groupby('Contract')['Churn Label'].value_counts(normalize=True).unstack()['Yes']*100
churn_by_contract.plot(kind='bar',color=['#F44336','#FF9800','#4CAF50'])
plt.title('Churn Rate by Contract Type')
plt.ylabel('Churn Rate(%)')
plt.xlabel('Contract')
plt.xticks(rotation=0)
plt.show()

df.columns

import matplotlib.pyplot as plt

churn_by_tenure = df.groupby('Tenure Months')['Churn Label'].value_counts(normalize=True).unstack()['Yes'] * 100

plt.figure(figsize=(12, 5))
churn_by_tenure.plot(kind='line', marker='o', color='#2196F3')
plt.title('Churn Rate by Tenure in Months')
plt.ylabel('Churn Rate (%)')
plt.xlabel('Tenure (Months)')
plt.grid(True, alpha=0.3)
plt.show()

